name: "Deploy"

on:
  push:
    branches:
      - production

jobs:
  tf-tests:
    name: "Terraform Tests"
    uses: ./.github/workflows/tf-tests.yml
    secrets: inherit

  tf-plan:
    name: "Terraform Plan"
    uses: ./.github/workflows/tf-plan.yml
    secrets: inherit

  tf-apply:
    name: "Terraform Apply"
    uses: ./.github/workflows/tf-apply.yml
    needs: [tf-tests, tf-plan]
    secrets: inherit

  done:
    name: "Deployment complete"
    needs: [tf-apply]
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        if: vars.ZULIP_ORG != ''
        with:
         api-key: ${{ secrets.ZULIP_BOT_API_KEY }}
         email: ${{ secrets.ZULIP_BOT_EMAIL }}
         organization-url: https://${{ vars.ZULIP_ORG }}.zulipchat.com
         type: stream
         to: github
         topic: ${{ github.event.repository.name }}
         content: |
          [${{ github.event.repository.name }}](${{ github.server_url }}/${{ github.repository }}) was deployed to production:
          [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
