name: "Deploy"

on:
  push:
    branches:
      - production

jobs:
  tf-tests:
    name: "Terraform Tests"
    uses: ./.github/workflows/tf-tests.yml
    secrets: inherit

  tf-plan:
    name: "Terraform Plan"
    uses: ./.github/workflows/tf-plan.yml
    secrets: inherit

  notify-start:
    name: 'Notify Zulip (start)'
    uses: ./.github/workflows/zulip-notify.yml
    needs: [tf-plan]
    secrets: inherit
    with:
      message: Starting deployment of [${{ github.event.repository.name }}](${{ github.server_url }}/${{ github.repository }}) ...

  tf-apply:
    name: "Terraform Apply"
    uses: ./.github/workflows/tf-apply.yml
    needs: [tf-tests, tf-plan]
    secrets: inherit

  done:
    name: "Deployment complete"
    uses: ./.github/workflows/zulip-notify.yml
    needs: [tf-apply]
    secrets: inherit
    with:
      message: |
        [${{ github.event.repository.name }}](${{ github.server_url }}/${{ github.repository }}) was deployed to production:
        [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
