name: "Pull Request"

on:
  pull_request:

jobs:
  tf-tests:
    name: "Terraform Tests"
    uses: ./.github/workflows/tf-tests.yml
    secrets: inherit

  tf-plan:
    name: "Terraform Plan"
    uses: ./.github/workflows/tf-plan.yml
    secrets: inherit

  done:
    name: "PR checks complete"
    needs: [tf-tests, tf-plan]
    runs-on: ubuntu-latest
    steps:
      - run: "true"
